/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author RODX & JonhDuranM
 */
public class Interfaz extends javax.swing.JPanel {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_InputMoney = new javax.swing.JLabel();
        jComboBox_ChooseMoney = new javax.swing.JComboBox<>();
        jButton_StartAcction = new javax.swing.JButton();
        jTextField_InputMoney = new javax.swing.JTextField();
        jLabel_ChooseMoney = new javax.swing.JLabel();
        jComboBox_ChooseMoney1 = new javax.swing.JComboBox<>();
        jLabel_ChooseMoney1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel_InputMoney.setText("Valor ");

        jComboBox_ChooseMoney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ChooseMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ChooseMoneyActionPerformed(evt);
            }
        });

        jButton_StartAcction.setText("Cambiar");
        jButton_StartAcction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartAcctionActionPerformed(evt);
            }
        });

        jTextField_InputMoney.setText("Ingrese el valor a cambiar");
        jTextField_InputMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InputMoneyActionPerformed(evt);
            }
        });

        jLabel_ChooseMoney.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel_ChooseMoney.setText("Seleccione su moneda principal");

        jComboBox_ChooseMoney1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ChooseMoney1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ChooseMoney1ActionPerformed(evt);
            }
        });

        jLabel_ChooseMoney1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel_ChooseMoney1.setText("Seleccione su moneda de cambio");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 2, 24)); // NOI18N
        jLabel1.setText("Convertidor de Moneda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_InputMoney)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_ChooseMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox_ChooseMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_ChooseMoney1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox_ChooseMoney1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jButton_StartAcction)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_ChooseMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ChooseMoney))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_ChooseMoney1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ChooseMoney1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_InputMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton_StartAcction)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ChooseMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ChooseMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ChooseMoneyActionPerformed

    private void jComboBox_ChooseMoney1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ChooseMoney1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ChooseMoney1ActionPerformed

    private void jTextField_InputMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InputMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InputMoneyActionPerformed

    private void jButton_StartAcctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartAcctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_StartAcctionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_StartAcction;
    private javax.swing.JComboBox<String> jComboBox_ChooseMoney;
    private javax.swing.JComboBox<String> jComboBox_ChooseMoney1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ChooseMoney;
    private javax.swing.JLabel jLabel_ChooseMoney1;
    private javax.swing.JLabel jLabel_InputMoney;
    private javax.swing.JTextField jTextField_InputMoney;
    // End of variables declaration//GEN-END:variables

    
}